### PR TITLE
feat(interceptor): add fastify support to set headers

### PR DESCRIPTION
**Pull request by acal11**
Added a header-set check to support fastify

### CODE REVIEW

**Comment by acal11** [comment]
Found that the interceptor does not execute if guards are being used in the application which deny a request, therefore I created a guard version of the interceptor. There is no breaking change here.

**Comment by kevinsproles** [comment]
I also need this: specifically the guard rather than the interceptor.

@ozkanonur can we merge this in?

**Comment by Andre-InfoTrack** [comment]
> I also need this: specifically the guard rather than the interceptor.
> 
> 
> 
> @ozkanonur can we merge this in?

I created a fork of this repo back before it got a new maintainer which includes the interceptor, you can look into that if it doesn't get merged.

**Comment by ozkanonur** [comment]
> I also need this: specifically the guard rather than the interceptor.
> 
> @ozkanonur can we merge this in?

What is the reason ?
I can't merge this, there are so many things that have been changed.

**Comment by kevinsproles** [comment]
Because I'd like my rate limiter to execute first, before the guards.

1) To mitigate brute force attacks on the guards.
2) To mitigate overwhelming the authentication layer.

**Pull request closed without merging**
